version: '3.8'

services:
  web:
    build:
      context: ./physioexercises
      dockerfile: Dockerfile
    command: gunicorn physioexercises.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/physioexercises/staticfiles
      - media_volume:/usr/src/physioexercises/mediafiles

    expose:
      - 8000
    env_file:
      - ./.env.prod
    
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/physioexercises/staticfiles
      - media_volume:/usr/src/physioexercises/mediafiles


    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
