version: '3.8'

services:
  web:
    build:
      context: ./physioexercises
      dockerfile: Dockerfile
    command: gunicorn physioexercises.wsgi:application --bind 0.0.0.0:8000

    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    
  
  