# Generated by Django 5.0.1 on 2024-04-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="image",
            field=models.ImageField(
                default="None", upload_to="images", verbose_name="Exercise Image"
            ),
            preserve_default=False,
        ),
    ]
